# Generated by Django 5.2.5 on 2025-08-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
