# Generated by Django 5.2.6 on 2026-02-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_user_deposit'),
        ('wallet', '0004_remove_wallettransaction_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
