# Generated by Django 5.2.6 on 2026-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='deposit',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
