# Generated by Django 5.2.6 on 2026-02-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_deposit_approval_status_deposit_recieved'),
        ('wallet', '0005_withdrawalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawal_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recipient', to='wallet.withdrawalaccount')),
            ],
        ),
    ]
