# Generated by Django 5.2.6 on 2026-03-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_transferrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
