# Generated by Django 5.2.12 on 2026-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_withdrawal_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('monnify', 'Monnify')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('config_data', models.JSONField(default=dict, help_text='{"secret_key": "...", "public_key": "...", "contract_code": "...", "base_url": "..."}')),
                ('use_for_deposits', models.BooleanField(default=True)),
                ('use_for_withdrawals', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
            },
        ),
    ]
