# Generated by Django 5.2.12 on 2026-04-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_deposit_processed_by_deposit_remarks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferRecipient',
        ),
    ]
