# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_delete_transferrecipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentGatewayConfig',
        ),
        migrations.CreateModel(
            name='PaystackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paystack Configuration',
                'verbose_name_plural': 'Paystack Configuration',
            },
        ),
    ]
