# Generated by Django 5.2.6 on 2026-02-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_email_verified_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='channel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
