# Generated by Django 5.2.6 on 2026-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_otp_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='closed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
