# Generated by Django 5.2.6 on 2026-03-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_closed_at_user_closed_reason_user_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tier',
        ),
    ]
