# Generated by Django 5.2.12 on 2026-04-01 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_bvn_user_face_verification_url_user_id_card_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='face_verification_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_card_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_notes',
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('id_image_url', models.URLField()),
                ('face_image_url', models.URLField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('time_accepted', models.DateTimeField(blank=True, null=True)),
                ('time_rejected', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'KYC Records',
            },
        ),
    ]
