# Generated by Django 5.2.12 on 2026-04-01 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_bvn_remove_user_face_verification_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_kycs', to=settings.AUTH_USER_MODEL),
        ),
    ]
