# Generated by Django 5.2.6 on 2026-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='service_type',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('tv', 'TV'), ('education', 'Education'), ('internet', 'Internet'), ('transfer', 'Wallet Transfer'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
