# Generated by Django 5.2.12 on 2026-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('none', 'None'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('all', 'All Channels (SMS, WhatsApp, Email)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Account Activation'), ('reset', 'Password Reset'), ('2fa', 'Two-Factor Authentication'), ('admin_operation', 'Admin Sensitive Operation')], max_length=20),
        ),
    ]
