# Generated by Django 5.2.12 on 2026-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_google_id_user_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='face_image_url',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='id_image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='kyc',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/face/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/id/'),
        ),
    ]
