# Generated by Django 5.2.6 on 2026-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_kyc_face_image_url_remove_kyc_id_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('none', 'None'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('all', 'All Channels (SMS, WhatsApp, Email)')], default='all', max_length=20),
        ),
    ]
