# Generated by Django 5.2.12 on 2026-04-09 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_two_factor_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUpgradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_to_agent_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged to upgrade a Customer to Agent.', max_digits=10)),
                ('customer_to_developer_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged to upgrade a Customer directly to Developer.', max_digits=10)),
                ('agent_to_developer_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged to upgrade an Agent to Developer.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable self-service role upgrades.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Upgrade Configuration',
                'verbose_name_plural': 'Role Upgrade Configuration',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent/Reseller'), ('developer', 'Developer'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='RoleUpgradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(max_length=20)),
                ('to_role', models.CharField(max_length=20)),
                ('fee_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upgraded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_upgrade_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Upgrade Log',
                'verbose_name_plural': 'Role Upgrade Logs',
                'ordering': ['-upgraded_at'],
            },
        ),
    ]
