# Generated by Django 5.2.12 on 2026-04-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_role_upgrade_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent/Reseller'), ('developer', 'Developer'), ('staff', 'Staff'), ('teacher', 'Teacher')], default='customer', max_length=20),
        ),
    ]
