# Generated by Django 5.2.6 on 2026-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent/Reseller'), ('developer', 'Developer'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
