services:
  - type: web
    name: data-app-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: data-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.10.12

  - type: cron
    name: vtu-automation-job
    env: python
    schedule: "*/5 * * * *"
    buildCommand: ./build.sh
    startCommand: python manage.py vtu_automation
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: data-app-db
          property: connectionString
      - key: DEBUG
        value: "False"

databases:
  - name: data-app-db
    plan: free
