# Generated by Django 5.2.6 on 2025-10-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0003_virtualaccount_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Summary Dashboard',
                'verbose_name_plural': 'Summary Dashboard',
                'managed': False,
                'proxy': True,
            },
            bases=('wallet.wallet',),
        ),
    ]
