# Generated by Django 5.2.6 on 2026-02-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='provider_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='provider_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='provider_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
