# Generated by Django 5.2.6 on 2026-02-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_siteconfig_provider_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CASHOUT', 'Cashout (Paystack to Bank)'), ('VTU_FUNDING', 'VTU Wallet Funding')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cashout_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cashout_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cashout_bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cashout_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vtu_funding_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vtu_funding_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vtu_funding_bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vtu_funding_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
