# Generated by Django 5.2.6 on 2026-02-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_systemtransaction_siteconfig_cashout_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='cashout_account_name',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='cashout_account_number',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='cashout_bank_code',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='cashout_bank_name',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='vtu_funding_bank_code',
        ),
    ]
