# Generated by Django 5.2.6 on 2026-02-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_remove_siteconfig_cashout_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='provider_account_name',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='provider_account_number',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='provider_bank_name',
        ),
    ]
