# Generated by Django 5.2.6 on 2026-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_remove_siteconfig_provider_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='automatic_withdrawal',
            field=models.BooleanField(default=False, help_text='If enabled, withdrawals will be processed automatically via Paystack.'),
        ),
    ]
