# Generated by Django 5.2.12 on 2026-04-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_siteconfig_automatic_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='withdrawals_enabled',
            field=models.BooleanField(default=True, help_text='Global toggle to enable or disable user withdrawals.'),
        ),
    ]
