# Generated by Django 5.2.6 on 2026-04-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_siteconfig_withdrawals_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='airtime_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='data_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='education_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='electricity_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tv_active',
            field=models.BooleanField(default=True),
        ),
    ]
