# Generated by Django 5.2.6 on 2026-04-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_siteconfig_airtime_active_siteconfig_data_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='auto_refund_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_retry_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='delayed_tx_detection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='delayed_tx_timeout_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='notify_admin_on_failure',
            field=models.BooleanField(default=True),
        ),
    ]
