# Generated by Django 5.2.12 on 2026-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_siteconfig_auto_refund_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('tv', 'TV'), ('electricity', 'Electricity'), ('education', 'Education'), ('internet', 'Internet')], max_length=20, unique=True)),
                ('cashback_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percentage', 'Percentage (%)')], default='flat', max_length=20)),
                ('cashback_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='agent_referral_commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='agent_referral_commission_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='agent_referral_cycle',
            field=models.CharField(choices=[('always', 'Always'), ('once', 'Once'), ('never', 'Never')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='agent_referral_trigger',
            field=models.CharField(choices=[('signup', 'On Signup'), ('credit', 'On Credit'), ('transaction', 'On Transaction')], default='signup', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_create_virtual_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_create_wallet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cashback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='deposit_charge_fixed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='deposit_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enforce_2fa_for_staff',
            field=models.BooleanField(default=False, help_text='If enabled, all staff users must pass 2FA to access admin features.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='signup_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='signup_bonus_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='user_referral_commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='user_referral_commission_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='user_referral_cycle',
            field=models.CharField(choices=[('always', 'Always'), ('once', 'Once'), ('never', 'Never')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='user_referral_trigger',
            field=models.CharField(choices=[('signup', 'On Signup'), ('credit', 'On Credit'), ('transaction', 'On Transaction')], default='signup', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='withdrawal_charge_fixed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='withdrawal_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
