# Generated by Django 5.2.12 on 2026-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_servicecashback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Email Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='fcm_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Push (FCM) Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable SMS Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable WhatsApp Notifications'),
        ),
    ]
