# Generated by Django 5.2.12 on 2026-04-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_siteconfig_email_enabled_siteconfig_fcm_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='developer_upgrade_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount charged to upgrade to developer status.', max_digits=12),
        ),
    ]
