# Generated by Django 5.2.12 on 2026-04-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_siteconfig_developer_upgrade_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='agent_upgrade_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount charged to upgrade to agent status.', max_digits=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='agent_upgrade_kyc_required',
            field=models.BooleanField(default=False, help_text='If enabled, user must be KYC verified to upgrade to agent.'),
        ),
    ]
