# Generated by Django 5.2.12 on 2026-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0014_siteconfig_agent_upgrade_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='agent_pricing_mode',
            field=models.CharField(choices=[('flat', 'Flat Reduction'), ('percentage', 'Percentage Reduction')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='agent_pricing_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount or percent to reduce for agents based on pricing mode.', max_digits=12),
        ),
    ]
