# Generated by Django 5.2.12 on 2026-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0015_siteconfig_agent_pricing_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='agent_pricing_mode',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='agent_pricing_value',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='airtime_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='data_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='education_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='electricity_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='internet_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tv_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
