# Generated by Django 5.2.6 on 2026-02-14 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_user_deposit'),
        ('wallet', '0003_virtualaccount_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='payment',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='deposit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transaction', to='payments.deposit'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
