from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.decorators import action
from drf_spectacular.utils import extend_schema_view, extend_schema
from users.models import User
from admin_api.serializers import AdminReferralSerializer
from admin_api.permissions import CanManageUsers
from django.db.models import Count, Sum, Q

@extend_schema_view(
    list=extend_schema(tags=["Admin Referrals"]),
    retrieve=extend_schema(tags=["Admin Referrals"]),
)
class AdminReferralViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet to manage and view referral relationships.
    Lists users who have referred others, ordered by the total value of transactions generated by their referrals.
    """
    permission_classes = [CanManageUsers]
    serializer_class = AdminReferralSerializer

    def get_queryset(self):
        return User.objects.annotate(
            referred_user_count=Count('referrals', distinct=True),
            total_referral_earnings=Sum('referral_earnings_amount'),
            total_referral_transaction_value=Sum(
                'referrals__purchases__amount', 
                filter=Q(referrals__purchases__status='SUCCESS')
            )
        ).filter(referred_user_count__gt=0).order_by('-total_referral_transaction_value')

    @extend_schema(
        tags=["Admin Referrals"],
        summary="Detailed referral breakdown for a user",
        description="Fetch a list of all users referred by this user and their aggregate stats."
    )
    @action(detail=True, methods=['get'], url_path='details')
    def details(self, request, pk=None):
        user = self.get_object()
        referrals = user.referrals.annotate(
            total_purchases_value=Sum('purchases__amount', filter=Q(purchases__status='SUCCESS')),
            purchase_count=Count('purchases', filter=Q(purchases__status='SUCCESS'))
        ).all()
        
        data = {
            "referrer": {
                "id": user.id,
                "phone_number": user.phone_number,
                "full_name": f"{user.first_name} {user.last_name}",
                "referral_code": user.referral_code
            },
            "referrals": [{
                "id": r.id,
                "phone_number": r.phone_number,
                "full_name": f"{r.first_name} {r.last_name}",
                "date_joined": r.created_at,
                "total_purchases_value": r.total_purchases_value or 0,
                "purchase_count": r.purchase_count or 0
            } for r in referrals],
            "total_referral_count": referrals.count(),
            "grand_total_transaction_value": user.total_referral_transaction_value or 0
        }
        return Response(data)
