# Generated by Django 5.2.6 on 2025-10-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('data', 'Data'), ('airtime', 'Airtime')], max_length=50),
        ),
    ]
