# Generated by Django 5.2.6 on 2025-09-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_network_plan_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='service_id',
            new_name='variation_code',
        ),
        migrations.AddField(
            model_name='network',
            name='service_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
