# Generated by Django 5.2.6 on 2026-01-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_purchase_purchase_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataplan',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='data_plan',
        ),
        migrations.RenameField(
            model_name='airtimenetwork',
            old_name='name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='airtimenetwork',
            name='maximum_amount',
        ),
        migrations.RemoveField(
            model_name='airtimenetwork',
            name='minimum_amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='airtime_type',
        ),
        migrations.AddField(
            model_name='purchase',
            name='airtime_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.airtimenetwork'),
        ),
        migrations.CreateModel(
            name='DataVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variation_id', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='orders.dataservice')),
            ],
            options={
                'verbose_name': 'Data Variation',
                'verbose_name_plural': 'Data Variations',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='data_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.datavariation'),
        ),
        migrations.DeleteModel(
            name='DataNetwork',
        ),
        migrations.DeleteModel(
            name='DataPlan',
        ),
    ]
