# Generated by Django 5.2.6 on 2025-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_service_id_plan_variation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='network',
        ),
        migrations.AddField(
            model_name='plan',
            name='service_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='service_provider',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('smileVoice', 'Smile Voice'), ('smialeBundle', 'Smile Bundle'), ('other', 'Other')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='service_type',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('smileVoice', 'Smile Voice'), ('smialeBundle', 'Smile Bundle'), ('other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
