# Generated by Django 5.2.6 on 2026-01-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dataservice_remove_dataplan_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='airtime_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.airtimenetwork'),
        ),
    ]
