# Generated by Django 5.2.6 on 2026-01-13 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_purchase_airtime_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELectricityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('data', 'Data'), ('airtime', 'Airtime'), ('electricity', 'Electricity'), ('tv', 'TV Subscription')], max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='electricity_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.electricityservice'),
        ),
        migrations.CreateModel(
            name='TVVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variation_id', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('package_bouquet', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='orders.tvservice')),
            ],
            options={
                'verbose_name': 'TV Variation',
                'verbose_name_plural': 'TV Variations',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='tv_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.tvvariation'),
        ),
    ]
