# Generated by Django 5.2.6 on 2025-10-04 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_airtimenetwork_datanetwork_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasale',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='datasale',
            name='user',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficiary', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('airtime_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airtime_sales', to='orders.airtimenetwork')),
                ('data_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.dataplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AirtimeSale',
        ),
        migrations.DeleteModel(
            name='DataSale',
        ),
    ]
