# Generated by Django 5.2.6 on 2026-02-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_electricityservice_tvservice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricityservice',
            options={'verbose_name': 'Electricity Service', 'verbose_name_plural': 'Electricity Services'},
        ),
        migrations.AlterModelOptions(
            name='tvservice',
            options={'verbose_name': 'TV Service', 'verbose_name_plural': 'TV Services'},
        ),
        migrations.AddField(
            model_name='airtimenetwork',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
        migrations.AddField(
            model_name='airtimenetwork',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=10),
        ),
        migrations.AddField(
            model_name='airtimenetwork',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
