# Generated by Django 5.2.6 on 2025-10-04 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_datasale_plan_remove_datasale_user_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='data_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sales', to='orders.dataplan'),
        ),
    ]
