# Generated by Django 5.2.6 on 2026-02-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_electricityservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimenetwork',
            name='discount',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='airtimenetwork',
            name='max_amount',
            field=models.CharField(default='200000', max_length=10),
        ),
        migrations.AlterField(
            model_name='airtimenetwork',
            name='min_amount',
            field=models.CharField(default='50', max_length=10),
        ),
        migrations.CreateModel(
            name='ElectricityVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variation_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='orders.electricityservice')),
            ],
            options={
                'verbose_name': 'Electricity Variation',
                'verbose_name_plural': 'Electricity Variations',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='electricity_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.electricityvariation'),
        ),
    ]
