# Generated by Django 5.2.6 on 2026-02-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_airtimenetwork_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmileService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Smile Service',
                'verbose_name_plural': 'Smile Services',
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('data', 'Data'), ('airtime', 'Airtime'), ('electricity', 'Electricity'), ('tv', 'TV Subscription'), ('smile', 'Smile Subscription')], max_length=50),
        ),
        migrations.CreateModel(
            name='SmileVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variation_id', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='orders.smileservice')),
            ],
            options={
                'verbose_name': 'Smile Variation',
                'verbose_name_plural': 'Smile Variations',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='smile_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.smilevariation'),
        ),
    ]
