# Generated by Django 5.2.6 on 2026-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_smileservice_alter_purchase_purchase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
