# Generated by Django 5.2.6 on 2026-02-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_purchase_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smilevariation',
            name='service',
        ),
        migrations.DeleteModel(
            name='SmileService',
        ),
    ]
