# Generated by Django 5.2.6 on 2026-02-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_smilevariation_service_delete_smileservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
