# Generated by Django 5.2.6 on 2026-02-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_purchase_purchased_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityvariation',
            name='discount',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='electricityvariation',
            name='max_amount',
            field=models.CharField(default='200000', max_length=10),
        ),
        migrations.AddField(
            model_name='electricityvariation',
            name='min_amount',
            field=models.CharField(default='1000', max_length=10),
        ),
    ]
