# Generated by Django 5.2.6 on 2026-03-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_purchase_initiated_by_purchase_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
