# Generated by Django 5.2.6 on 2026-03-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_purchase_order_remark_purchase_provider_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='order_remark',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='status_code',
        ),
    ]
