# Generated by Django 5.2.12 on 2026-04-01 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('tv', 'Cable TV'), ('smile', 'Smile'), ('education', 'Education')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Service Routing',
                'verbose_name_plural': 'Service Routings',
            },
        ),
        migrations.CreateModel(
            name='VTUProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vtpass', 'VTPass'), ('clubkonnect', 'ClubKonnect'), ('payflex', 'Payflex'), ('alrahuz', 'Alrahuz'), ('mobilenig', 'MobileNIG'), ('otapay', 'Otapay'), ('arewaglobal', 'Arewa Global'), ('mightydata', 'MightyData'), ('smedata', 'SMEDATA.NG'), ('mobilevtu', 'MobileVTU'), ('aimtoget', 'Aimtoget'), ('nata', 'Nata API'), ('amigo', 'Amigo'), ('vtuorg', 'vtu.org')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config_data', models.JSONField(default=dict, help_text='{"api_key": "...", "public_key": "...", "secret_key": "...", "base_url": "..."}')),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('auto_refund_on_failure', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VTU Provider Config',
                'verbose_name_plural': 'VTU Provider Configs',
            },
        ),
        migrations.CreateModel(
            name='ServiceFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('service_routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.servicerouting')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.vtuproviderconfig')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('service_routing', 'provider')},
            },
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='fallbacks',
            field=models.ManyToManyField(related_name='fallback_for_services', through='orders.ServiceFallback', to='orders.vtuproviderconfig'),
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='primary_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_services', to='orders.vtuproviderconfig'),
        ),
    ]
