# Generated by Django 5.2.12 on 2026-04-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_promocode_purchasepromoused'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('data', 'Data'), ('airtime', 'Airtime'), ('electricity', 'Electricity'), ('tv', 'TV Subscription'), ('smile', 'Smile Subscription'), ('education', 'Education')], max_length=50),
        ),
        migrations.CreateModel(
            name='EducationVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variation_id', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='orders.educationservice')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='education_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.educationvariation'),
        ),
    ]
