# Generated by Django 5.2.12 on 2026-04-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_educationservice_alter_purchase_purchase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimenetwork',
            name='agent_discount',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='datavariation',
            name='agent_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='educationvariation',
            name='agent_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='electricityvariation',
            name='agent_discount',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='smilevariation',
            name='agent_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tvvariation',
            name='agent_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
