# Generated by Django 5.2.12 on 2026-04-01 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_airtimenetwork_agent_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_token',
            new_name='token',
        ),
        migrations.AddField(
            model_name='airtimenetwork',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airtimenetwork',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airtime_networks', to='orders.vtuproviderconfig'),
        ),
        migrations.AddField(
            model_name='dataservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_services', to='orders.vtuproviderconfig'),
        ),
        migrations.AddField(
            model_name='datavariation',
            name='plan_type',
            field=models.CharField(choices=[('sme', 'SME'), ('corporate', 'Corporate'), ('gifting', 'Gifting'), ('direct', 'Direct'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='educationservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_services', to='orders.vtuproviderconfig'),
        ),
        migrations.AddField(
            model_name='educationvariation',
            name='plan_type',
            field=models.CharField(choices=[('sme', 'SME'), ('corporate', 'Corporate'), ('gifting', 'Gifting'), ('direct', 'Direct'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='electricityservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='electricityservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_services', to='orders.vtuproviderconfig'),
        ),
        migrations.AddField(
            model_name='electricityvariation',
            name='plan_type',
            field=models.CharField(choices=[('sme', 'SME'), ('corporate', 'Corporate'), ('gifting', 'Gifting'), ('direct', 'Direct'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='orders.vtuproviderconfig'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smilevariation',
            name='plan_type',
            field=models.CharField(choices=[('sme', 'SME'), ('corporate', 'Corporate'), ('gifting', 'Gifting'), ('direct', 'Direct'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='tvservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tvservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv_services', to='orders.vtuproviderconfig'),
        ),
        migrations.AddField(
            model_name='tvvariation',
            name='plan_type',
            field=models.CharField(choices=[('sme', 'SME'), ('corporate', 'Corporate'), ('gifting', 'Gifting'), ('direct', 'Direct'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='SmileService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Smile', max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smile_services', to='orders.vtuproviderconfig')),
            ],
        ),
        migrations.AddField(
            model_name='smilevariation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='orders.smileservice'),
        ),
        migrations.CreateModel(
            name='PurchaseBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('tv', 'TV Subscription'), ('education', 'Education'), ('smile', 'Smile Subscription')], max_length=20)),
                ('identifier', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Beneficiary',
                'verbose_name_plural': 'Purchase Beneficiaries',
                'unique_together': {('user', 'service_type', 'identifier')},
            },
        ),
    ]
