# Generated by Django 5.2.6 on 2026-04-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_rename_purchased_token_purchase_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerouting',
            name='agent_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount/percentage to add to cost for agents', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='auto_refund_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='customer_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount/percentage to add to cost for users', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='fallback_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='pricing_mode',
            field=models.CharField(choices=[('fixed_margin', 'Fixed Margin'), ('defined', 'Defined Pricing')], default='defined', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='retry_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='retry_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='auto_funding_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='min_funding_balance',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12),
        ),
    ]
