# Generated by Django 5.2.6 on 2026-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_servicerouting_agent_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationvariation',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='electricityvariation',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount the provider charges the platform', max_digits=10),
        ),
        migrations.AddField(
            model_name='smilevariation',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tvvariation',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount the provider charges the platform', max_digits=10),
        ),
    ]
