# Generated by Django 5.2.6 on 2026-04-02 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_educationvariation_cost_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmileVariation',
            new_name='InternetVariation',
        ),
        migrations.RenameModel(
            old_name='SmileService',
            new_name='InternetService',
        ),
        migrations.AlterModelOptions(
            name='internetvariation',
            options={'verbose_name': 'Internet Variation', 'verbose_name_plural': 'Internet Variations'},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='smile_variation',
            new_name='internet_variation',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('data', 'Data'), ('airtime', 'Airtime'), ('electricity', 'Electricity'), ('tv', 'TV Subscription'), ('internet', 'Internet Subscription'), ('education', 'Education')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasebeneficiary',
            name='service_type',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('tv', 'TV Subscription'), ('education', 'Education'), ('internet', 'Internet Subscription')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerouting',
            name='service',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('tv', 'Cable TV'), ('internet', 'Internet Sub'), ('education', 'Education')], max_length=20, unique=True),
        ),

        migrations.AlterField(
            model_name='internetservice',
            name='service_name',
            field=models.CharField(default='Internet Subscription', max_length=100),
        ),
        migrations.AlterField(
            model_name='internetservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internet_services', to='orders.vtuproviderconfig'),
        ),
        migrations.AlterField(
            model_name='internetvariation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='orders.internetservice'),
        ),
    ]
