# Generated by Django 5.2.6 on 2026-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_internetvariation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vtuproviderconfig',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vtuproviderconfig',
            name='config_data',
            field=models.JSONField(default=dict, help_text='Additional settings for the provider'),
        ),
        migrations.AlterField(
            model_name='vtuproviderconfig',
            name='name',
            field=models.CharField(choices=[('vtpass', 'VTPass'), ('clubkonnect', 'ClubKonnect'), ('alrahuz', 'Alrahuz Data'), ('mobilenig', 'MobileNig'), ('otapay', 'OTAPAY'), ('arewa_global', 'Arewa Global'), ('mightydata', 'MightyData'), ('smedata', 'SMEDATA.NG'), ('mobilevtu', 'MobileVTU'), ('aimtoget', 'Aimtoget'), ('nata', 'Nata API'), ('amigo', 'Amigo'), ('vtuorg', 'vtu.org'), ('payflex', 'PayFlex')], max_length=20, unique=True),
        ),
    ]
