# Generated by Django 5.2.6 on 2026-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_vtuproviderconfig_api_key_vtuproviderconfig_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
