# Generated by Django 5.2.6 on 2026-04-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_purchase_last_error_purchase_retry_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vtuproviderconfig',
            old_name='private_key',
            new_name='secret_key',
        ),
        migrations.RemoveField(
            model_name='vtuproviderconfig',
            name='config_data',
        ),
    ]
