# Generated by Django 5.2.12 on 2026-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_rename_private_key_vtuproviderconfig_secret_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtimenetwork',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='dataservice',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='educationservice',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='electricityservice',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='internetservice',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='tvservice',
            name='image_url',
        ),
        migrations.AddField(
            model_name='airtimenetwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='networks/'),
        ),
        migrations.AddField(
            model_name='dataservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='educationservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='electricityservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='internetservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='tvservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
