# Generated by Django 5.2.12 on 2026-04-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_remove_airtimenetwork_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicVTUProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('api_key_header', models.CharField(default='Authorization', max_length=100)),
                ('api_key_prefix', models.CharField(blank=True, default='Token ', max_length=100)),
                ('api_key', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('request_format', models.CharField(choices=[('json', 'JSON'), ('params', 'Query Params')], default='json', max_length=10)),
                ('response_format', models.CharField(choices=[('json', 'JSON')], default='json', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='vtuproviderconfig',
            name='name',
            field=models.CharField(choices=[('vtpass', 'VTPass'), ('clubkonnect', 'ClubKonnect'), ('arewa_global', 'Arewa Global'), ('alrahuz', 'Alrahuz Data')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DynamicOperationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('get_networks', 'Get Networks'), ('get_variations', 'Get Variations/Packages'), ('purchase', 'Purchase Service'), ('verify', 'Verify Status')], max_length=50)),
                ('endpoint_path', models.CharField(help_text='e.g. /api/data/', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10)),
                ('request_params', models.JSONField(blank=True, default=dict, help_text='Mapping from our internal names to theirs')),
                ('static_params', models.JSONField(blank=True, default=dict, help_text='Always sent with request')),
                ('success_condition', models.JSONField(blank=True, default=dict, help_text="e.g. {'field': 'status', 'value': 'true'}")),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='orders.dynamicvtuprovider')),
            ],
        ),
    ]
