# Generated by Django 5.2.12 on 2026-04-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_dynamicvtuprovider_alter_vtuproviderconfig_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicoperationconfig',
            name='success_condition',
        ),
        migrations.AddField(
            model_name='dynamicoperationconfig',
            name='failure_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'status': 'fail'}"),
        ),
        migrations.AddField(
            model_name='dynamicoperationconfig',
            name='response_data_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Map provider fields to internal fields'),
        ),
        migrations.AddField(
            model_name='dynamicoperationconfig',
            name='success_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'status': 'success', 'code': 200}"),
        ),
        migrations.AlterField(
            model_name='dynamicoperationconfig',
            name='operation_type',
            field=models.CharField(choices=[('get_networks', 'Get Networks'), ('get_variations', 'Get Variations/Packages'), ('purchase', 'Purchase Service'), ('verify', 'Verify Status'), ('balance', 'Check Balance'), ('verify_customer', 'Verify Customer/Meter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vtuproviderconfig',
            name='name',
            field=models.CharField(choices=[('vtpass', 'VTPass'), ('clubkonnect', 'ClubKonnect'), ('arewa_global', 'Arewa Global'), ('alrahuz', 'Alrahuz Data'), ('smedata', 'SMEDATA.NG'), ('mobilenig', 'MobileNig'), ('mobilevtu', 'MobileVTU'), ('nata', 'Nata API'), ('amigo', 'Amigo'), ('vtuorg', 'vtu.org')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DynamicOperationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='Can use {api_key}, {phone}, etc.', max_length=500)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_headers', to='orders.dynamicoperationconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicOperationPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='Can use {phone}, {amount}, etc.', max_length=500)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_payload', to='orders.dynamicoperationconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicProviderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='Can use {api_key}', max_length=500)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_headers', to='orders.dynamicvtuprovider')),
            ],
        ),
    ]
