# Generated by Django 5.2.12 on 2026-04-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_airtimenetwork_agent_price_airtimenetwork_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtuproviderconfig',
            name='name',
            field=models.CharField(choices=[('vtpass', 'VTPass'), ('clubkonnect', 'ClubKonnect'), ('arewa_global', 'Arewa Global'), ('alrahuz', 'Alrahuz Data'), ('smedata', 'SMEDATA.NG'), ('mobilenig', 'MobileNig'), ('mobilevtu', 'MobileVTU'), ('nata', 'Nata API'), ('amigo', 'Amigo'), ('vtuorg', 'vtu.org'), ('flowpay', 'FlowPay')], max_length=20, unique=True),
        ),
    ]
