# Generated by Django 5.2.6 on 2026-04-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_usernotification_delete_notificationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationProviderConfig',
        ),
    ]
