# Generated by Django 5.2.12 on 2026-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_delete_notificationproviderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='use_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='use_fcm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='use_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='use_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(help_text='Default body. Use placeholders: {username}, {amount}, {reference}, {service}, {status}, {balance}'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='slug',
            field=models.SlugField(help_text='System identifier (e.g. wallet-funded, purchase-success)', unique=True),
        ),
    ]
