# Generated by Django 5.2.12 on 2026-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationtemplate_use_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='image_url',
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
